Application implementation
EreliaCorp/Sparkle pull request #11
Opened 2023-06-13 14:32 UTC by NotCampeur

2023-06-13 21:04 UTC, EreliaCorp commented on includes/graphics/linux/spk_window.hpp
> +		void resize(spk::Vector2Int p_size);
Pass the argument as const ref

2023-06-13 21:04 UTC, EreliaCorp commented on src/threading/spk_worker_pool.cpp
> +    WorkerPool::WorkerPool(std::wstring p_poolName, size_t p_nbWorker)
Pass the argument as const ref

2023-06-13 21:06 UTC, EreliaCorp requested changes
Multiples requests are formulated :
- Reformating some files
- Changing parameter to const ref
- adding the "p_" to some argument
- etc etc

2023-06-13 21:12 UTC, EreliaCorp commented on includes/application/modules/spk_abstract_module.hpp
> +	};
Maybe this class isn't necessary, as we do not use it as base class, maybe we should remove it

2023-06-13 21:13 UTC, EreliaCorp commented on includes/application/modules/windows/spk_API_module.hpp
> +		void update();
We should rename this method to something closer to what it does, like "pullMessage" or something like this

2023-06-13 21:13 UTC, EreliaCorp commented on includes/application/modules/linux/spk_API_module.hpp
> +		void update();
We should rename this method to something closer to what it does, like "pullMessage" or something like this

2023-06-14 11:12 UTC, NotCampeur commented on includes/application/concrete/windows/spk_graphical_application.hpp
> +			addJob([&](){ _APIModule->update(); });
postponed.

2023-06-14 13:21 UTC, EreliaCorp approved these changes

2023-06-14 13:21 UTC, EreliaCorp approved these changes
Review okay

2023-06-14 14:03 UTC, merged