Memento creation
EreliaCorp/Sparkle pull request #45
Opened 2023-07-02 17:14 UTC by EreliaCorp

2023-07-02 17:17 UTC, EreliaCorp commented on includes/design_pattern/spk_memento.hpp
> +		}
We do not want the DataBuffer to store the object at all. We want the Snapshot to contain defined section of the object, via a secondary classe Memento::Object or something. This object must describe what to do when saving or loading snapshot

2023-07-02 17:17 UTC, EreliaCorp commented on includes/design_pattern/spk_memento.hpp
> +			newSnapshot << p_state;
We need to use previously describe Memento::Object

2023-07-02 17:17 UTC, EreliaCorp commented on includes/design_pattern/spk_memento.hpp
> +			newSnapshot << p_state;
We probably should have a _save method

2023-07-02 17:19 UTC, EreliaCorp commented on playground/src/main.cpp
> +	}
Those two methods should be the _onSave and _onLoad method of the Memento::Object

2023-07-02 17:21 UTC, EreliaCorp reviewed
Need to create the Memento::Object

2023-07-03 08:36 UTC, Neyune requested changes
Apply Erelia recommandation

2023-07-04 13:58 UTC, EreliaCorp reviewed
Is that the problem

2023-07-04 13:59 UTC, closed without merging